#!groovy

properties([
    buildDiscarder(logRotator(daysToKeepStr: '20', numToKeepStr: '30')),

    [$class: 'GithubProjectProperty',
     projectUrlStr: 'https://github.com/euank/alexa-parrot'],

    pipelineTriggers([
      // Pull requests, with whitelisting/auth
      [$class: 'GhprbTrigger',
       adminlist: 'euank',
       cron: '*/1 * * * *',
       permitAll: false,
       displayBuildErrorsOnDownstreamBuilds: true,
       gitHubAuthId: 'dd528eca-0dbc-4c17-a4c6-8e8a2ba7f43d'],
    ])
])


node('docker') {
  stage('SCM') {
    checkout scm
  }

  stage('Build') {
    sh '''#!/bin/bash -ex
      docker run -v $(pwd):/go/src/github.com/euank/alexa-parrot \
        -w /go/src/github.com/euank/alexa-parrot \
        golang:1.8 \
        make
    '''
  }
}
